document.write("Agente : " + info.agente)
document.write(" , Java Activo : " + info.javaActivo)
document.write(" , Plataforma : " +info.plataforma)
document.write(" , Vendedor : " +info.vendedor)
document.write(" , Version : " +info.version)